name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  hatch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: pipx install hatch

      - run: hatch run all:test

  uv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/0.1.29/uv-installer.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - run: |
          uv venv
          uv pip install nox
          .venv/bin/nox

